server:
  port: 8082

spring:
  profiles:
    active: test
---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello World


---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/dcbapp-test
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello World
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: "env,beans"

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello World
